### ISSUE TITLE
Implement comparison operators

### ISSUE THREAD

**Issue by chrisdjscott** [chrisdjscott/DACE.jl#1]
Implement comparison operators for compatibility with DifferentialEquations, such as <, >, etc

These should be based on the constant part initially.

**Comment by afossa** [comment]
I overloaded the comparison operators based on the constant part of the polynomial here 53b16a511def0388ba3cbcb2b2d10c9c08793b12
I can make a PR if you agree.

**Comment by chrisdjscott** [comment]
@afossa this looks great, please make a PR

**Comment by chrisdjscott** [comment]
We could add some tests for the comparison operators too (although I'm happy to do that after the PR to save you time)
