### ISSUE TITLE
Using DACE with DifferentialEquations

### ISSUE THREAD

**Issue by afossa** [chrisdjscott/DACE.jl#5]
As of 9801d29684200c53f05e207b3932cb0d4016acb8 DACE can be interfaced with both fix and variable step size ODE integrators found in `DifferentialEquations`.

To achieve this, I added `DiffEqBase` as dependency of DACE, since I had to overload `DiffEqBase.value()` to act like `DACE.cons()`. See 784e0df848d955a4718bed6fb9c067693544a0cf for details.

I did some quick tests with a variable step integrator, and the time series are very close to those obtained with `Float64` as type for the state components. I also checked the final state and Jacobian w.r.t. `ForwardFiff`, and the two are in well agreement.

I can make a PR if you agree.

**Comment by chrisdjscott** [comment]
@afossa this looks great too, please make a PR

Do you have an example script (could be something simple) of using DACE with DifferentialEquations that we can add to the examples directory?

**Comment by afossa** [comment]
Yes, I have one based on Jack's work. I'll clean it up, commit and make a PR.

**Comment by afossa** [comment]
PR is up, checking compatibility. I also opened this one https://github.com/a-ev/dace/pull/1 for changes in the underline code.
